// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL =
  process.env.NEXT_PUBLIC_TRUCKS_SUPABASE_URL ?? process.env.TRUCKS_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  process.env.NEXT_PUBLIC_TRUCKS_SUPABASE_PUBLISHABLE_KEY ??
  process.env.NEXT_PUBLIC_TRUCKS_SUPABASE_ANON_KEY ??
  process.env.TRUCKS_SUPABASE_PUBLISHABLE_KEY ??
  process.env.TRUCKS_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Trucks Supabase environment variables. Define NEXT_PUBLIC_TRUCKS_SUPABASE_URL and NEXT_PUBLIC_TRUCKS_SUPABASE_PUBLISHABLE_KEY.'
  );
}

// Import the trucks Supabase client like this:
// import { supabase } from "@/integrations/supabase_trucks/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
